---
name: Release Drafter

on:
  workflow_call:

jobs:
  draft:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: release-drafter/release-drafter@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
