---
name: metal-stack component release
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  go-build:
    uses: ./.github/workflows/go-build.yaml
    secrets: inherit
    with:
      build-command: make go
      artifact-files: |
        bin/

  spell-check:
    uses: ./.github/workflows/spell-check.yaml

  draft:
    uses: ./.github/workflows/release-drafter.yaml

  release-assets:
    uses: ./.github/workflows/release-assets.yaml
    needs: go-build
    with:
      artifact-ids: ${{ needs.go-build.outputs.go-build-artifacts }}

  helm-chart:
    uses: ./.github/workflows/helm-chart.yaml
    with:
      chart-path: test-chart
      container-image-values-patch: a.b.image
